version: '2'

services:

  # ポート8000でリッスンしているサーバ
  go-app:
    build: 
      context: ./go
      dockerfile: Dockerfile

  reverse-proxy:
    image: httpd:latest
    ports: 
      - 8080:80
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    environment:
      PROXY_PATH: /
      PROXY_URL: http:go-app:8080/
      USER_ID: "forwarder"